In [1]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
data = pd.read_csv('/content/drive/MyDrive/UnemploymentProject/CleanDatasets/bin_5_cleaned_future_rates.csv')
data.head()
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1730 entries, 0 to 1729
Data columns (total 33 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Month                   1730 non-null   int64
 1   Year                    1730 non-null   int64
 2   State                   1730 non-null   object
 3   County                  1730 non-null   object
 4   Fire_Size               1730 non-null   float64
 5   Rate                    1730 non-null   float64
 6   Number of Employees     1730 non-null   float64
 7   CPI                     1730 non-null   float64
 8   Interest Rate           1730 non-null   float64
 9   NumWorkStoppages        1730 non-null   int64
 10  NumWorkersInStoppages   1730 non-null   int64
 11  WorkStoppagesTotalDays  1730 non-null   int64
 12  Log_Fire_Size           1730 non-null   float64
 13  Log10_Fire_Size         1730 non-null   float64
 14  Sqrt_Fire_Size          1730 non-null   float64
 15  Crt_Fire_Size           1730 non-null   float64
 16  Log_Fire_Size_Bin       1730 non-null   object
 17  Date                    1730 non-null   object
 18  Rate_1M_Later           1730 non-null   float64
 19  Rate_2M_Later           1730 non-null   float64
 20  Rate_3M_Later           1730 non-null   float64
 21  Rate_4M_Later           1730 non-null   float64
 22  Rate_5M_Later           1730 non-null   float64
 23  Rate_6M_Later           1730 non-null   float64
 24  Rate_7M_Later           1730 non-null   float64
 25  Rate_8M_Later           1730 non-null   float64
 26  Rate_9M_Later           1730 non-null   float64
 27  Rate_10M_Later          1730 non-null   float64
 28  Rate_11M_Later          1730 non-null   float64
 29  Rate_12M_Later          1730 non-null   float64
 30  Rate_1M_Prev            1730 non-null   float64
 31  Rate_2M_Prev            1730 non-null   float64
 32  Rate_3M_Prev            1730 non-null   float64
dtypes: float64(24), int64(5), object(4)
memory usage: 446.1+ KB

In [8]:
for index, row in data.iterrows():
    year = row['Year']
    county = row['County']
    month = row['Month']

    for months_prev in [1, 2, 3]:
        if month - months_prev <= 0:
            prev_month = 12 + (month - months_prev)
            prev_year = year - 1
        else:
            prev_month = month - months_prev
            prev_year = year
        prev_rate = data[(data['Year'] == prev_year) &
                   (data['County'] == county) &
                   (data['Month'] == prev_month)]['Rate']

        if not prev_rate.empty:
            data.at[index, f'Rate_{months_prev}M_Prev'] = prev_rate.iloc[0]
        else:
            data.at[index, f'Rate_{months_prev}M_Prev'] = None

data.head(20)

,Month,Year,State,County,Fire_Size,Rate,Number of Employees,CPI,Interest Rate,NumWorkStoppages,...,Rate_6M_Later,Rate_7M_Later,Rate_8M_Later,Rate_9M_Later,Rate_10M_Later,Rate_11M_Later,Rate_12M_Later,Rate_1M_Prev,Rate_2M_Prev,Rate_3M_Prev
0,4,1992,MS,Attala,159.0,12.8,108331.0,139.5,3.73,35,...,7.7,10.0,9.9,10.2,10.9,8.2,10.3,NaN,NaN,NaN
1,4,1992,MS,Jackson,356.0,6.6,108331.0,139.5,3.73,35,...,5.5,6.7,6.4,5.9,5.4,5.3,6.3,NaN,NaN,NaN
2,4,1992,MS,Harrison,979.0,7.3,108331.0,139.5,3.73,35,...,4.2,5.1,4.9,5.0,7.4,7.2,7.5,NaN,NaN,NaN
3,4,1992,MS,Hancock,146.0,7.1,108331.0,139.5,3.73,35,...,5.3,5.3,5.8,7.1,6.6,6.4,5.8,NaN,NaN,NaN
4,4,1992,MS,Forrest,257.5,6.3,108331.0,139.5,3.73,35,...,4.6,4.5,4.2,4.0,4.8,5.2,3.9,NaN,NaN,NaN
5,4,1992,MS,Marshall,307.0,10.8,108331.0,139.5,3.73,35,...,10.0,6.3,6.1,9.8,10.5,9.1,8.8,NaN,NaN,NaN
6,4,1992,MS,Pearl River,388.0,8.8,108331.0,139.5,3.73,35,...,6.1,6.4,6.6,6.4,6.0,6.1,7.0,NaN,NaN,NaN
7,4,1992,MS,Perry,167.0,11.8,108331.0,139.5,3.73,35,...,9.1,9.0,9.1,7.8,7.8,9.2,6.1,NaN,NaN,NaN
8,4,1992,SC,Dorchester,147.0,5.2,108331.0,139.5,3.73,35,...,5.6,4.3,4.0,4.8,5.2,4.3,2.8,NaN,NaN,NaN
9,4,1992,SC,Colleton,159.0,10.1,108331.0,139.5,3.73,35,...,11.7,11.1,10.6,10.1,6.6,6.7,6.5,NaN,NaN,NaN
10,4,1992,SC,Clarendon,758.0,11.1,108331.0,139.5,3.73,35,...,14.8,14.1,12.1,7.8,8.4,8.6,5.4,NaN,NaN,NaN
11,4,1992,SC,Orangeburg,120.5,8.1,108331.0,139.5,3.73,35,...,8.4,8.1,8.0,8.7,9.3,7.9,7.1,NaN,NaN,NaN
12,4,1992,WV,Lincoln,220.0,16.0,108331.0,139.5,3.73,35,...,12.0,12.8,12.6,13.6,12.3,10.4,13.1,NaN,NaN,NaN
13,4,1992,SC,Berkeley,612.1,5.4,108331.0,139.5,3.73,35,...,6.2,6.8,5.9,5.5,6.2,6.4,6.5,NaN,NaN,NaN
14,4,1992,NC,Onslow,255.0,4.8,108331.0,139.5,3.73,35,...,4.1,3.9,3.4,6.3,4.2,5.1,4.6,NaN,NaN,NaN
15,5,1992,MT,Lincoln,248.2,14.6,109137.0,139.7,3.82,35,...,6.9,9.6,7.3,5.7,4.5,5.8,8.6,16.0,NaN,NaN
16,5,1992,MT,Blaine,350.0,7.1,109137.0,139.7,3.82,35,...,8.8,8.6,7.9,10.0,7.7,7.8,6.8,NaN,NaN,NaN
17,5,1992,NC,Robeson,216.0,10.1,109137.0,139.7,3.82,35,...,8.6,7.2,7.4,7.5,7.1,7.9,7.3,NaN,NaN,NaN
18,5,1992,MS,Pearl River,191.0,9.5,109137.0,139.7,3.82,35,...,6.4,6.6,6.4,6.0,6.1,7.0,5.4,8.8,NaN,NaN
19,5,1992,MO,Shannon,232.0,7.3,109137.0,139.7,3.82,35,...,8.1,8.1,7.2,8.5,7.7,7.9,5.0,NaN,NaN,NaN

In [7]:
data = data.dropna()
data.head()
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1730 entries, 0 to 1729
Data columns (total 33 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Month                   1730 non-null   int64
 1   Year                    1730 non-null   int64
 2   State                   1730 non-null   object
 3   County                  1730 non-null   object
 4   Fire_Size               1730 non-null   float64
 5   Rate                    1730 non-null   float64
 6   Number of Employees     1730 non-null   float64
 7   CPI                     1730 non-null   float64
 8   Interest Rate           1730 non-null   float64
 9   NumWorkStoppages        1730 non-null   int64
 10  NumWorkersInStoppages   1730 non-null   int64
 11  WorkStoppagesTotalDays  1730 non-null   int64
 12  Log_Fire_Size           1730 non-null   float64
 13  Log10_Fire_Size         1730 non-null   float64
 14  Sqrt_Fire_Size          1730 non-null   float64
 15  Crt_Fire_Size           1730 non-null   float64
 16  Log_Fire_Size_Bin       1730 non-null   object
 17  Date                    1730 non-null   object
 18  Rate_1M_Later           1730 non-null   float64
 19  Rate_2M_Later           1730 non-null   float64
 20  Rate_3M_Later           1730 non-null   float64
 21  Rate_4M_Later           1730 non-null   float64
 22  Rate_5M_Later           1730 non-null   float64
 23  Rate_6M_Later           1730 non-null   float64
 24  Rate_7M_Later           1730 non-null   float64
 25  Rate_8M_Later           1730 non-null   float64
 26  Rate_9M_Later           1730 non-null   float64
 27  Rate_10M_Later          1730 non-null   float64
 28  Rate_11M_Later          1730 non-null   float64
 29  Rate_12M_Later          1730 non-null   float64
 30  Rate_1M_Prev            1730 non-null   float64
 31  Rate_2M_Prev            1730 non-null   float64
 32  Rate_3M_Prev            1730 non-null   float64
dtypes: float64(24), int64(5), object(4)
memory usage: 446.1+ KB

In [5]:
data.to_csv("/content/drive/MyDrive/UnemploymentProject/CleanDatasets/bin_5_cleaned_future_prev_rates.csv.csv", index=False)